const DATABASE_NAME= "AICafe";
const BOT_DATA_COLLECTION_NAME= "botdata";
const ORDERS_COLLECTION_NAME= "orders";
const RESERVATIONS_COLLECTION_NAME= "reservations";
const REVIEWS_COLLECTION_NAME= "reviews";

module.exports = {
  DATABASE_NAME,
  BOT_DATA_COLLECTION_NAME,
  ORDERS_COLLECTION_NAME,
  RESERVATIONS_COLLECTION_NAME,
  REVIEWS_COLLECTION_NAME
}